### ISSUE TITLE
Change Twitter to X

### ISSUE THREAD

**Issue by Berge-Repositories** [custom-twemoji/custom-twemoji-api#113]
X is the new Twitter.

**Comment by blakegearin** [comment]
Twemoji still has Twitter branding on its website and is still on the original domain: https://twemoji.twitter.com

Further, I want to make it clear I don't support Twitter anymore, and encourage others to use open protocols like [ActivityPub](https://en.wikipedia.org/wiki/ActivityPub) (see [Mastodon](https://joinmastodon.org)) for socializing online. Twemoji's licensing could change at any time given how heavy-handed their monetization strategy has been recently.

To what extent this impacts the API and its maintenance is still to be determined. I have considered deprecating this project in favor of supporting [OpenMoji](https://openmoji.org), though I'm not sure how feasible that is.
